# Default values for go-vue-websockets.

replicaCount: 1

image:
  repository: cvasquez/go-vue-websockets
  tag: latest
  pullPolicy: Always

service:
  name: go-vue-websockets
  type: NodePort
  externalPort: 8080
  internalPort: 8080
  port: 8080

livenessProbe:                                                                                                                                                                                                                                                                                                               
  enabled: true                                                                                                                                                                                                                                                                                                              
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10                                                                                                                                                                                                                                                                                                          
  timeoutSeconds: 5                                                                                                                                                                                                                                                                                                          
  successThreshold: 1                                                                                                                                                                                                                                                                                                        
  failureThreshold: 3                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                             
readinessProbe:                                                                                                                                                                                                                                                                                                              
  enabled: true                                                                                                                                                                                                                                                                                                              
  path: /ready
  initialDelaySeconds: 10
  periodSeconds: 10                                                                                                                                                                                                                                                                                                          
  timeoutSeconds: 5                                                                                                                                                                                                                                                                                                          
  successThreshold: 1                                                                                                                                                                                                                                                                                                        
  failureThreshold: 3  

ingress:                                                                                                                                                                                                                                                                        
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx                                                                                                                                                                                                                                        
    kubernetes.io/tls-acme: "true"                                                                                                                                                                                                                                            
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: 'true'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      sub_filter '</head>' '<head> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-124246858-2"></script>
                                   <script>window.dataLayer = window.dataLayer || [];
                                   function gtag(){dataLayer.push(arguments);}
                                   gtag("js", new Date());
                                   gtag("config", "UA-124246858-2");</script>'; 

  path: /demo/vue-websocket-echo
  hosts:
    - cvasquez.dev
  tls: 
    - secretName: chart-example-tls                                                                                                                                                                                                                                            
      hosts:                                                                                                                                                                                                                                                                   
        - cvasquez.dev
        - www.cvasquez.dev

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
